const Data = [
  {
    id: 1,
    category: "education",
    icon: "icon-graduation",
    year: "2019 - present",
    title: "Bachelor's Degree",
    desc: "Bachelors of Information Technology (BIT), KIST College, Kamalpokhari, Kathmandu, Nepal.",
  },
  {
    id: 2,
    category: "education",
    icon: "icon-graduation",
    year: "2016 - 2018",
    title: "High School (+2)",
    desc: "Science (Physical Section), KIST College, Kamalpokhari, Kathmandu, Nepal.",
  },
  {
    id: 3,
    category: "education",
    icon: "icon-graduation",
    year: "2015",
    title: "School",
    desc: "Nepal Model School, Basundhara, Kathmandu, Nepal.",
  },
  {
    id: 4,
    category: "experience",
    icon: "icon-briefcase",
    year: "Comfortable",
    title: "Languages & Scripts",
    desc: "PHP, JavaScript, Java, HTML5, CSS3C, C++, C#",
  },
  {
    id: 5,
    category: "experience",
    icon: "icon-briefcase",
    year: "Comfortable",
    title: "Libraries",
    desc: "React, Node.js",
  },
  {
    id: 6,
    category: "experience",
    icon: "icon-briefcase",
    year: "Comfortable",
    title: "Framework",
    desc: "Laravel, Express, Bootstrap, .NET",
  },
  {
    id: 6,
    category: "experience",
    icon: "icon-briefcase",
    year: "Comfortable",
    title: "Database",
    desc: "MySQL, PostgreSQL, SQL Server, phpMyAdmin",
  },
  {
    id: 6,
    category: "experience",
    icon: "icon-briefcase",
    year: "Comfortable",
    title: "Version Control",
    desc: "Git, GitHub",
  },
  {
    id: 7,
    category: "experience",
    icon: "icon-briefcase",
    year: "Comfortable",
    title: "Cloud Service",
    desc: "C panel, Netlify, Vercel",
  },
];
export default Data;
